### ISSUE TITLE
Using $CIRCLE_TAG is failing

### ISSUE THREAD

**Issue by christianhaller3000** [h-matsuo/circleci-orb-github-release#3]
Hi @h-matsuo , I'm glad to find your cool orb.

````
release:
    description: Create dummy file and publish a new release tagged `vX.Y.Z`.
    executor: github-release/default
    steps:
      - attach_workspace:
          at: .
      - github-release/create:
          tag: $CIRCLE_TAG
          title: Version $CIRCLE_TAG
          description: This release is version vX.Y.Z .
          file-path: ./index-macos
````

Do you have any idea why this is not working?

````
#!/bin/bash -eo pipefail
ghr \
  --token $GITHUB_TOKEN \
  --username $CIRCLE_PROJECT_USERNAME \
  --repository $CIRCLE_PROJECT_REPONAME \
  --commitish $CIRCLE_SHA1 \
  --name "Version $CIRCLE_TAG" \
  --body "This release is version vX.Y.Z ." \
   \
   \
    $CIRCLE_TAG ./index-macos
Invalid argument: you must set TAG and PATH name.
Exited with code 13
````
